### PR TITLE
feat(refactor): ✨ better title, missing dependencies and better req.txt shell commands added

### PR DESCRIPTION
**Pull request by onuralpszr**
### What does this PR do?

Based on issue #226, I made same few changes to the original file to enhance the user experience for anyone attempting to use it.

- better title, 
- missing dependencies
- better req.txt generation shell commands added

cc @merveenoyan and @stevhliu.

### CODE REVIEW

**Review by stevhliu — APPROVED** [review]
LGTM thanks! Also pinging @sergiopaniego for a quick review as the chef of the recipe 🤗

**Comment by onuralpszr** [comment]
> LGTM thanks! Also pinging @sergiopaniego for a quick review as the chef of the recipe 🤗 

Thank you very much 😊 Waiting for @sergiopaniego to check as well.

**Review by sergiopaniego — APPROVED** [review]
Thanks a lot for the review @onuralpszr! I've added a few comments :smile:

**Comment by merveenoyan** [comment]
<p>I think no need for adding this since this recipe is pretty general</p>

---

 <a href='https://app.reviewnb.com/huggingface/cookbook/pull/228/discussion/#comment-2456526939'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by merveenoyan** [comment]
left only one comment :)

**Comment by onuralpszr** [comment]
@sergiopaniego I fixed the output images (I didn't mean to touch it but some weird reason git/reviewnb show as changes but  they are there) as for the title @merveenoyan  and @sergiopaniego please decide :) 

But my reason was adding this because title is not clear which model we fine-tuning to so I wanted to make sure we clear on this instructions and title. 

Thank you both of you 🤗

**Comment by sergiopaniego** [comment]
I’d stick with @merveenoyan 's suggestion. :smiley:

**Comment by onuralpszr** [comment]
@stevhliu  side note : the moment you merge we see doc builder message, I think there is something wrong with this too

**Pull request merged**
