### PR TITLE
new notebook: Information Extraction with Haystack and NuExtract

### PR DESCRIPTION
**Pull request by anakin87**
# What does this PR do?

Add a new notebook: "Information Extraction with Haystack and NuExtract".

In the notebook, we create an Information Extraction pipeline with the [Haystack open-source framework](https://haystack.deepset.ai) and the [NuExtract open model](https://huggingface.co/numind/NuExtract).

Then we extract structured data and derive insights from startups' funding announcements.

(@tuanacelik)

## Who can review?
@merveenoyan @stevhliu

## Notes on visualization

I think some rendered outputs/visualizations are quite important to make this notebook clear and engaging (e.g., the pipeline diagram, the dataframe, and the graph visualization). 

As far as I know, https://github.com/huggingface/cookbook/issues/48 is still valid.
If there is a way to preview what the notebook would look like in the HF site, we can check it out and then add the missing visualization using images in markdown cells.
If a preview is not possible, I would be more than happy to add those images in markdown cells to ensure that the notebook looks nice and understandable.

### CODE REVIEW

**Review by merveenoyan — APPROVED** [review]
great PR tbh I couldn't find anything to comment on, would like to wait for @stevhliu to comment and we can merge

**Comment by anakin87** [comment]
<p>done!</p>

---

 <a href='https://app.reviewnb.com/huggingface/cookbook/pull/150/discussion/#comment-2236141871'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by anakin87** [comment]
@merveenoyan thx for the quick review!

About **visualization**: while the cell outputs are displayed correctly in ReviewNB, I suspect that some of them won't be displayed in https://huggingface.co/learn/cookbook

We have two options:
- once the PR is ok, merge it and if the relevant outputs  (pipeline diagram, dataframe, and graph) are not displayed on the website, create another PR, following the approach for images outlined [here](https://github.com/huggingface/cookbook?tab=readme-ov-file#creating-a-pull-request)
- do it in advance

LMK...

**Review by stevhliu — COMMENTED** [review]
Very nice job and great visualizations! Once the build PR documentation check passes, we can preview whether the visualizations work and then merge 🙂

**Comment by anakin87** [comment]
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/huggingface/cookbook/pull/150/discussion/#comment-2243227104'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by anakin87** [comment]
@stevhliu I made a change to not display `ByteStream` objects, which I think are problematic.
Can you please try rerunning the documentation build workflow?

**Comment by stevhliu** [comment]
The doc preview is currently down but everything else looks good and ready to merge! If the visualization doesn't render, then let's go with option 2 and open a PR and add the images as outlined [here](https://github.com/huggingface/cookbook?tab=readme-ov-file#creating-a-pull-request)

**Pull request merged**
