### PR TITLE
Added Cookbook for Multimodal Retrieval-Augmented Generation (RAG) with Document Retrieval (ColPali) and Vision Language Models (VLMs)

### LINKED ISSUE #209: New Multimodal Retrieval-Augmented Generation (RAG) with Document Retrieval (ColPali) and Vision Language Models (VLMs)
**Multimodal RAG** is gaining significant interest with recent advancements such as **ColPali** and **Qwen2-VL**. These technologies are enabling powerful new capabilities for retrieval-augmented generation systems. For instance, there are already intriguing [examples](https://github.com/merveenoyan/smol-vision/blob/main/ColPali_%2B_Qwen2_VL.ipynb).

I propose adding a new recipe to this repository that provides an in-depth explanation of **Multimodal RAG** and includes a comprehensive usage example to help users better understand and implement these techniques.

### PR DESCRIPTION
**Pull request by sergiopaniego**
# What does this PR do?

Fixes #209

## Who can review?

@merveenoyan and @stevhliu.

### CODE REVIEW

**Comment by sergiopaniego** [comment]
Thanks a lot for the review!! 😃
I've updated the branch with the latest changes from `main` to make it mergeable.

**Review by merveenoyan — APPROVED** [review]
two small comments but otherwise looks good to me! thank you:)

**Comment by sergiopaniego** [comment]
Thanks for the review! I've updated the notebook addressing the comments 😄 

It may be ready to be merged!

**Comment by sergiopaniego** [comment]
<p>Updated!</p>

---

 <a href='https://app.reviewnb.com/huggingface/cookbook/pull/210/discussion/#comment-2391976865'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sergiopaniego** [comment]
<p>Thanks for pointing out the mismatching! 7B :)</p>

---

 <a href='https://app.reviewnb.com/huggingface/cookbook/pull/210/discussion/#comment-2391976894'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
