### PR TITLE
Added HF login cell to `Build an agent with tool-calling superpowers 🦸 using Transformers Agents` recipe

### LINKED ISSUE #229: Add HF login cell to `Build an agent with tool-calling superpowers 🦸 using Transformers Agents` notebook
In [Build an agent with tool-calling superpowers 🦸 using Transformers Agents](https://huggingface.co/learn/cookbook/agents) recipe, login is required since it uses the HF Inference API.

The login cell may be added so a newcomer can easily reproduce the recipe 😄

### PR DESCRIPTION
**Pull request by sergiopaniego**
# What does this PR do?

Fixes #229

## Who can review?

@merveenoyan and @stevhliu.

### CODE REVIEW

**Review by stevhliu — APPROVED** [review]
Thanks! 🤗

**Comment by sergiopaniego** [comment]
Updated 😄

**Comment by stevhliu** [comment]
Do you mind getting the [latest changes](https://github.com/huggingface/cookbook/pull/236) from `main` to fix the doc-builder issue?

**Comment by sergiopaniego** [comment]
Updated! Thanks again for the reminder 🤗

**Comment by sergiopaniego** [comment]
Updated! Let's see if this is the one 🤞 🤗

**Pull request merged**
