### PR TITLE
Enterprise cookbook gradio: remove cell outputs

### PR DESCRIPTION
**Pull request by dmaniloff**
# What does this PR do?

Removes unnecessary cell outputs.

## Who can review?

@stevhliu.

### CODE REVIEW

**Comment by dmaniloff** [comment]
cc/ @MoritzLaurer

**Review by MoritzLaurer — APPROVED** [review]
LGTM!

**Comment by dmaniloff** [comment]
@MoritzLaurer thank you for merging! do you know if deployment is instant or if it takes a bit to reflect on the site?

it looks like this hasn't taken effect, as i can still see the cell outputs (eg after pip install): https://huggingface.co/learn/cookbook/enterprise_cookbook_gradio

**Comment by MoritzLaurer** [comment]
seems like it just took a few minutes. the cell outputs seem to be gone now

**Pull request merged**
