### PR TITLE
Added Fine-Tuning a smol 🤏 VLM (SmolVLM) using DPO (TRL) on a Consumer GPU recipe

### LINKED ISSUE #254: New Fine-Tuning a smol 🤏 VLM (SmolVLM) using DPO (TRL) on a Consumer GPU recipe 🧑‍🍳️
I propose adding a new recipe demonstrating how to fine-tune the [SmolVLM](https://huggingface.co/HuggingFaceTB/SmolVLM-Instruct) using DPO and [TRL](https://github.com/huggingface/trl) on a Consumer GPU.

Same idea as in #245 but using DPO!

### PR DESCRIPTION
**Pull request by sergiopaniego**
# What does this PR do?

Fixes #254

## Who can review?

@merveenoyan and @stevhliu

### CODE REVIEW

**Review by stevhliu — APPROVED** [review]
Very nice, your SmolVLM series is awesome!

**Review by merveenoyan — APPROVED** [review]
left some nits, otherwise looks good! 💗🫰🏻

**Comment by sergiopaniego** [comment]
<p>I've updated the Space to use the official one and added a note here :) <a href="https://huggingface.co/HuggingFaceTB/SmolVLM-Instruct-DPO" target="_blank">https://huggingface.co/HuggingFaceTB/SmolVLM-Instruct-DPO</a></p>

---

 <a href='https://app.reviewnb.com/huggingface/cookbook/pull/255/discussion/#comment-2546613627'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sergiopaniego** [comment]
Thank you for your feedback @stevhliu @merveenoyan @burtenshaw 🤗 

I've updated the notebook accordingly.

**Pull request merged**
