### PR TITLE
Added Multi-agent RAG system recipe 🧑‍🍳️

### LINKED ISSUE #237: New Multi-agent RAG System recipe 🧑‍🍳️
I propose adding a new recipe to this repository that explains how to create a Multi-agent RAG System.
The idea comes from a recent [post](https://weaviate.io/blog/what-is-agentic-rag) 🤗

### PR DESCRIPTION
**Pull request by sergiopaniego**
# What does this PR do?

Fixes #237

## Who can review?

@merveenoyan and @stevhliu

cc @aymeric-roucher

### CODE REVIEW

**Comment by aymeric-roucher** [comment]
Great work @sergiopaniego, thanks a lot. A few suggestions then lgtm!

**Comment by stevhliu** [comment]
Very nice and comprehensive recipe showcasing the different tasks!

**Comment by sergiopaniego** [comment]
<p>I'm using the latest changes to incorporate recent updates that haven't yet been included in an official release. For example: <a href="https://github.com/huggingface/transformers/pull/34683" target="_blank">https://github.com/huggingface/transformers/pull/34683</a> &amp;&amp; <a href="https://github.com/huggingface/transformers/pull/34687" target="_blank">https://github.com/huggingface/transformers/pull/34687</a> :)</p>

---

 <a href='https://app.reviewnb.com/huggingface/cookbook/pull/238/discussion/#comment-2494079228'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sergiopaniego** [comment]
<p>Thanks for the suggestion! </p><p>I tried using the Space you shared but it generates some errors because it uses an old Gradio version. I duplicated the Space, updated the Gradio version and it works. The error is generated in <code>transformers/agents/tools.py</code> in <code>if not parameter["parameter_has_default"]:</code> . If you feel this is something that should be addressed, maybe we can take a deeper look at it in transformers :)  </p>

---

 <a href='https://app.reviewnb.com/huggingface/cookbook/pull/238/discussion/#comment-2494079308'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sergiopaniego** [comment]
Thanks for the feedback @aymeric-roucher @stevhliu! 
I've updated the recipe accordingly 🤗

**Comment by stevhliu** [comment]
Do you mind getting the [latest changes](https://github.com/huggingface/cookbook/pull/236) from `main` to fix the doc-builder issue?

**Comment by sergiopaniego** [comment]
Thanks for the reminder @stevhliu 😄 done!

**Review by stevhliu — APPROVED** [review]
Thanks again @sergiopaniego! ❤️

**Pull request merged**
