### PR TITLE
Add notebook demonstrating RAG with LlamaIndex

### PR DESCRIPTION
**Pull request by jinnovation**
# What does this PR do?

This notebook is a "spin-off" of sorts from
@MKhalusova's notebook on RAG with LangChain and
Zephyr. Here, we demonstrate the use of LlamaIndex as a counterpart to LangChain, demonstrating its
flexibility for RAG-specific use cases.

## Who can review?

@MKhalusova

### CODE REVIEW

**Comment by jinnovation** [comment]
Thanks in advance for the review @MKhalusova 😇

**Review by MKhalusova — COMMENTED** [review]
Really nice notebook! Since you mention that the documents have not been chunked during loading, perhaps, it's worth mentioning when the chunking happens.

As I understand, the documents are chunked when ingested into the VectorStoreIndex (feel free to correct if that's wrong). 
Maybe also worth mentioning the defaults for the chunk size and overlap.

**Comment by jinnovation** [comment]
> Really nice notebook! Since you mention that the documents have not been chunked during loading, perhaps, it's worth mentioning when the chunking happens.

Good catch. Added a note to that effect.

> As I understand, the documents are chunked when ingested into the VectorStoreIndex (feel free to correct if that's wrong). Maybe also worth mentioning the defaults for the chunk size and overlap.

Done.

**Review by MKhalusova — COMMENTED** [review]
The notebook looks good, but I see that you added the `*.epub` files. There's no need to keep them in the repo as you give the readers instructions on how to get them. Let's remove these files.

**Comment by jinnovation** [comment]
Sorry about that! Accidentally commit-all'd. Will remove.

**Review by MKhalusova — APPROVED** [review]
Thanks for adding the notebook and iterating over the feedback! It's ready to merge now.

**Pull request merged**
