### PR TITLE
Object Detection Fine tuning cookbook with Deployment in Spaces, and Gradio API Integration

### LINKED ISSUE #188: New Object Detection Fine tuning cookbook with Deployment in Spaces, and Gradio API Integration
Currently, the cookbooks lack recipes for vision tasks. I propose adding a notebook in this area, as suggested in the [Call for Contributions #82](https://github.com/huggingface/cookbook/issues/82#issuecomment-2286654022) thread.

This notebook would include:

* Fine tuning of an object detection model.
* Deployment of the model in HF Spaces.
* Access to the Space via the Gradio API integration.

### PR DESCRIPTION
**Pull request by sergiopaniego**
# What does this PR do?

Fixes #188.

This notebook includes:

* Fine tuning of an object detection model.
* Deployment of the model in HF Spaces.
* Access to the Space via the Gradio API integration.

## Who can review?

@merveenoyan and @stevhliu.

### CODE REVIEW

**Review by merveenoyan — APPROVED** [review]
You're a master chef! 🧑🏻‍🍳 I have no comments, went through all of it, I'd like to wait for @stevhliu's review

**Review by stevhliu — APPROVED** [review]
Great job creating an end-to-end notebook!

**Comment by sergiopaniego** [comment]
Thank you both for your feedback :smile:!
I've addressed the comments and updated the branch with the latest changes from `main`.

**Comment by stevhliu** [comment]
Oops, looks like the WandB and Gradio logos also need to be removed!

**Comment by sergiopaniego** [comment]
Removed! 🤞

**Pull request merged**
